const data = [
  {
    productId: 1,
    pname: "Fresh Tomato",
    pimage: "http://www.way2door.com/images/products/tamato.jpg",
    price: 60,
    sellPrice: 50,
    pUnit: "1Kg",
    mainCat: "Fresh_Vegetables",
    pdescription: "",
    deliveryCharge: 40,
    freeDeliveryMinOrderAmount: 500,
    quantity:1,
    total_price:60
  },
  {
    productId: 2,
    pname: "Potato Old",
    pimage: "http://www.way2door.com/images/products/potato.jpg",
    price: 30,
    sellPrice: 20,
    pUnit: "1Kg",
    mainCat: "Fresh_Vegetables",
    pdescription: "",
    deliveryCharge: 40,
    freeDeliveryMinOrderAmount: 500,
    quantity:1,
    total_price:30
  },
  {
    productId: 3,
    pname: "Onion",
    pimage: "http://www.way2door.com/images/products/onion.jpg",
    price: 50,
    sellPrice: 30,
    pUnit: "1Kg",
    mainCat: "Fresh_Vegetables",
    pdescription: "",
    deliveryCharge: 40,
    freeDeliveryMinOrderAmount: 500,
    quantity:1,
    total_price:50
  },
  {
    productId: 4,
    pname: "Green Chilli",
    pimage: "http://www.way2door.com/AllProducts/fruits_and_vegetables/Green%20Chilli.jpg",
    price: 20,
    sellPrice: 15,
    pUnit: "250 gm",
    mainCat: "Fresh_Vegetables",
    pdescription: "",
    deliveryCharge: 40,
    freeDeliveryMinOrderAmount: 500,
    quantity:1,
    total_price:20
  },
  {
    productId: 5,
    pname: "Garlic (Lehsun)",
    pimage: "http://www.way2door.com/images/products/garlic_lehsun.jpg",
    price: 60,
    sellPrice: 40,
    pUnit: "250 gm",
    mainCat: "Fresh_Vegetables",
    pdescription: "",
    deliveryCharge: 40,
    freeDeliveryMinOrderAmount: 500,
    quantity:1,
    total_price:60
  },
  {
    productId: 6,
    pname: "Shimla Mirch",
    pimage: "http://www.way2door.com/AllProducts/fruits_and_vegetables/Green%20Capsicum-way2door.jpg",
    price: 40,
    sellPrice: 20,
    pUnit: "250 gm",
    mainCat: "Fresh_Vegetables",
    pdescription: "",
    deliveryCharge: 40,
    freeDeliveryMinOrderAmount: 500,
    quantity:1,
    total_price:40
  },
  {
    productId: 7,
    pname: "Carrot",
    pimage: "http://www.way2door.com/AllProducts/fruits_and_vegetables/Orange%20Carrot-way2door.jpg",
    price: 50,
    sellPrice: 40,
    pUnit: "1Kg",
    mainCat: "Fresh_Vegetables",
    pdescription: "",
    deliveryCharge: 40,
    freeDeliveryMinOrderAmount: 500,
    quantity:1,
    total_price:50
  },
  {
    productId: 8,
    pname: "Coriander",
    pimage: "http://www.way2door.com/images/products/coriander.jpg",
    price: 30,
    sellPrice: 10,
    pUnit: "250 gm",
    mainCat: "Fresh_Vegetables",
    pdescription: "",
    deliveryCharge: 40,
    freeDeliveryMinOrderAmount: 500,
    quantity:1,
    total_price:30
  },
  {
    productId: 9,
    pname: "Pomegranate (Anaar)",
    pimage: "http://www.way2door.com/AllProducts/fruits_and_vegetables/Pomegranate (Anaar).jpg",
    price: 180,
    sellPrice: 155,
    pUnit: "1Kg",
    mainCat: "Fresh_Fruits",
    pdescription: "",
    deliveryCharge: 40,
    freeDeliveryMinOrderAmount: 500,
    quantity:1,
    total_price:180
  },
  {
    productId: 10,
    pname: "Cabbage",
    pimage: "http://www.way2door.com/AllProducts/fruits_and_vegetables/Cabbage-way2door.jpg",
    price: 30,
    sellPrice: 25,
    pUnit: "1 unit",
    mainCat: "Fresh_Vegetables",
    pdescription: "",
    deliveryCharge: 40,
    freeDeliveryMinOrderAmount: 500,
    quantity:1,
    total_price:30
  },
  {
    productId: 11,
    pname: "Cauliflower",
    pimage: "http://www.way2door.com/AllProducts/fruits_and_vegetables/Cauliflower.jpg",
    price: 50,
    sellPrice: 30,
    pUnit: "1 unit",
    mainCat: "Fresh_Vegetables",
    pdescription: "",
    deliveryCharge: 40,
    freeDeliveryMinOrderAmount: 500,
    quantity:1,
    total_price:50
  },
  {
    productId: 12,
    pname: "Guava ( Amrud )",
    pimage: "http://www.way2door.com/AllProducts/fruits_and_vegetables/Guava.jpg",
    price: 60,
    sellPrice: 50,
    pUnit: "1Kg",
    mainCat: "Fresh_Fruits",
    pdescription: "",
    deliveryCharge: 40,
    freeDeliveryMinOrderAmount: 500,
    quantity:1,
    total_price:60
  },
  {
    productId: 13,
    pname: "Papaya 1 KG",
    pimage: "http://www.way2door.com/AllProducts/fruits_and_vegetables/Papaya-way2door.jpg",
    price: 60,
    sellPrice: 55,
    pUnit: "1Kg",
    mainCat: "Fresh_Fruits",
    pdescription: "",
    deliveryCharge: 40,
    freeDeliveryMinOrderAmount: 500,
    quantity:1,
    total_price:60
  },
  {
    productId: 14,
    pname: "Green Coconut",
    pimage: "http://www.way2door.com/AllProducts/fruits_and_vegetables/Green Coconut-way@door.jpg",
    price: 50,
    sellPrice: 45,
    pUnit: "1 unit",
    mainCat: "Fresh_Fruits",
    pdescription: "",
    deliveryCharge: 40,
    freeDeliveryMinOrderAmount: 500,
    quantity:1,
    total_price:50
  },
  {
    productId: 15,
    pname: "Banana",
    pimage: "http://www.way2door.com/AllProducts/fruits_and_vegetables/Yellaki (Kathali Kala) Banana-way@door.jpg",
    price: 60,
    sellPrice: 50,
    pUnit: "12 unit",
    mainCat: "Fresh_Fruits",
    pdescription: "",
    deliveryCharge: 40,
    freeDeliveryMinOrderAmount: 500,
    quantity:1,
    total_price:60
  },
  {
    productId: 16,
    pname: "Kasmiri Apple",
    pimage: "http://www.way2door.com/AllProducts/fruits_and_vegetables/Kashmiri Apple-way2door.jpg",
    price: 160,
    sellPrice: 150,
    pUnit: "1Kg",
    mainCat: "Fresh_Fruits",
    pdescription: "",
    deliveryCharge: 40,
    freeDeliveryMinOrderAmount: 500,
    quantity:1,
    total_price:160
  },
  {
    productId: 17,
    pname: "Shimla Apple",
    pimage: "http://www.way2door.com/AllProducts/fruits_and_vegetables/Shimla Apple.jpg",
    price: 170,
    sellPrice: 150,
    pUnit: "1Kg",
    mainCat: "Fresh_Fruits",
    pdescription: "",
    deliveryCharge: 40,
    freeDeliveryMinOrderAmount: 500,
    quantity:1,
    total_price:170
  },
  {
    productId: 18,
    pname: "Potato Old",
    pimage: "http://www.way2door.com/images/products/potato.jpg",
    price: 30,
    sellPrice: 20,
    pUnit: "1Kg",
    mainCat: "Fresh_Vegetables",
    pdescription: "",
    deliveryCharge: 40,
    freeDeliveryMinOrderAmount: 500,
    quantity:1,
    total_price:30
  },
  {
    productId: 19,
    pname: "Onion",
    pimage: "http://www.way2door.com/images/products/onion.jpg",
    price: 50,
    sellPrice: 40,
    pUnit: "1Kg",
    mainCat: "Fresh_Vegetables",
    pdescription: "",
    deliveryCharge: 40,
    freeDeliveryMinOrderAmount: 500,
    quantity:1,
    total_price:50
  },
  {
    productId: 20,
    pname: "Large Round Brinjal (Bharta)",
    pimage: "http://www.way2door.com/AllProducts/fruits_and_vegetables/Large Round Brinjal (Bharta).jpg",
    price: 30,
    sellPrice: 20,
    pUnit: "1Kg",
    mainCat: "Fresh_Vegetables",
    pdescription: "",
    deliveryCharge: 40,
    freeDeliveryMinOrderAmount: 500,
    quantity:1,
    total_price:30
  },
  {
    productId: 21,
    pname: "Long Brinjal",
    pimage: "http://www.way2door.com/AllProducts/fruits_and_vegetables/Long Brinjal-way2door.jpg",
    price: 30,
    sellPrice: 15,
    pUnit: "1Kg",
    mainCat: "Fresh_Vegetables",
    pdescription: "",
    deliveryCharge: 40,
    freeDeliveryMinOrderAmount: 500,
    quantity:1,
    total_price:30
  },
  {
    productId: 22,
    pname: "Lady Finger",
    pimage: "http://www.way2door.com/images/products/lady_finger.jpg",
    price: 30,
    sellPrice: 15,
    pUnit: "250 gm",
    mainCat: "Fresh_Vegetables",
    pdescription: "",
    deliveryCharge: 40,
    freeDeliveryMinOrderAmount: 500,
    quantity:1,
    total_price:30
  },
  {
    productId: 23,
    pname: "Green Chilli",
    pimage: "http://www.way2door.com/AllProducts/fruits_and_vegetables/Green Chilli.jpg",
    price: 20,
    sellPrice: 15,
    pUnit: "250 gm",
    mainCat: "Fresh_Vegetables",
    pdescription: "",
    deliveryCharge: 40,
    freeDeliveryMinOrderAmount: 500,
    quantity:1,
    total_price:20
  },
  {
    productId: 24,
    pname: "Ginger (Adrak)",
    pimage: "http://www.way2door.com/images/products/ginger_adrak.jpg",
    price: 30,
    sellPrice: 20,
    pUnit: "250 gm",
    mainCat: "Fresh_Vegetables",
    pdescription: "",
    deliveryCharge: 40,
    freeDeliveryMinOrderAmount: 500,
    quantity:1,
    total_price:30
  },
  {
    productId: 25,
    pname: "Pointed gourd (Parval)",
    pimage: "http://www.way2door.com/AllProducts/fruits_and_vegetables/Pointed Gourd (Parval).jpg",
    price: 20,
    sellPrice: 10,
    pUnit: "250 gm",
    mainCat: "Fresh_Vegetables",
    pdescription: "",
    deliveryCharge: 40,
    freeDeliveryMinOrderAmount: 500,
    quantity:1,
    total_price:20
  },
  {
    productId: 26,
    pname: "Green Capsicum ( Shimla Mirch )",
    pimage: "http://www.way2door.com/AllProducts/fruits_and_vegetables/Green Capsicum-way2door.jpg",
    price: 40,
    sellPrice: 20,
    pUnit: "250 gm",
    mainCat: "Fresh_Vegetables",
    pdescription: "",
    deliveryCharge: 40,
    freeDeliveryMinOrderAmount: 500,
    quantity:1,
    total_price:40
  },
  {
    productId: 27,
    pname: "lemon ( Nimbu )",
    pimage: "http://www.way2door.com/AllProducts/vegetables/nibu-lemon-way2door.jpg",
    price: 15,
    sellPrice: 20,
    pUnit: "5 unit",
    mainCat: "Fresh_Vegetables",
    pdescription: "",
    deliveryCharge: 40,
    freeDeliveryMinOrderAmount: 500,
    quantity:1,
    total_price:15
  },
  {
    productId: 28,
    pname: "Apple (Washington)",
    pimage: "http://www.way2door.com/AllProducts/fruits_and_vegetables/Washington Apple-way2door.jpg",
    price: 155,
    sellPrice: 140,
    pUnit: "1Kg",
    mainCat: "Fresh_Fruits",
    pdescription: "",
    deliveryCharge: 40,
    freeDeliveryMinOrderAmount: 500,
    quantity:1,
    total_price:155
  },
  {
    productId: 29,
    pname: "Dates Crown premium",
    pimage: "http://www.way2door.com/AllProducts/fruits_and_vegetables/Date Crown Fard Dates-way2door.jpg",
    price: 230,
    sellPrice: 185,
    pUnit: "500 gm",
    mainCat: "Dry_Fruits",
    pdescription: "",
    deliveryCharge: 40,
    freeDeliveryMinOrderAmount: 500,
    quantity:1,
    total_price:230
  },
  {
    productId: 30,
    pname: "Eggs",
    pimage: "http://www.way2door.com/AllProducts/non_veg/non_veg_Eggs.jpg",
    price: 100,
    sellPrice: 85,
    pUnit: "12pc",
    mainCat: "Non_Veg",
    pdescription: "",
    deliveryCharge: 40,
    freeDeliveryMinOrderAmount: 500,
    quantity:1,
    total_price:100
  },

];
export default data;
